
path: /mnt/nas/users/vaibhavt/Active-Learning-Benchmarking/
train: train_images/
# train: images/test/
val: test_images/ # test -> val
# val: images/val_R2_merged_multiple/
# val: images/test/
# Classes`
# nc: 82  # number of classes
nc: 98
# names: ['anat_elli','anti_cerv','arct_coll','athe_macr','axis_axis','axis_porc','bats_bats','bird_bird','blan_blan','bos__fron','bos__gaur','bos__indi',
# 'bose_trag-Boselaphus tragocamelus','budo_taxi-Budorcas taxicolor','call_pyge-Callosciurus pygerythrus','came_came-Camel','cani_aure-Canis aureus',
# 'cani_lupu-Canis lupus','capr_hisp-Caprolagus hispidus','capr_thar-Capricornis thar','cato_temm-Catopuma temminckii','catt_catt-Cattle','catt_kill',
# 'cuon_alpi-Cuon alpinus','dome_cats-Domestic cat','dome_dogs-Domestic dog','elep_maxi-Elephas maximus','equu_caba-Equus caballus','feli_chau-Felis chaus',
# 'feli_sylv-Felis sylvestris','fran_pond-Francolinus pondicerianus','funa_palm-Funambulus palmarum','gall_gall-Gallus gallus','gall_lunu-Galloperdix lunulata',
# 'gall_sonn-Gallus sonneratii','gall_spad-Galloperdix spadicea','gaze_benn-Gazella bennettii','goat_sheep','hela_mala-Helarctos malayanus','herp_edwa-Herpestes edwardsii',
# 'herp_fusc-Herpestes fuscus','herp_smit-Herpestes smithii','herp_urva-Herpestes urva','herp_vitt-Herpestes vitticollis','homo_sapi','hyae_hyae-Hyaena hyaena',
# 'hyst_brac-Hystrix brachyura','hyst_indi-Hystrix indica','lept_java-Leptoptilos javanicus','lepu_nigr-Lepus nigricollis','lutr_lutr-Lutra lutra',
# 'lutr_pers-Lutrogale perspicillata','maca_arct-Macaca arctoides','maca_assa-Macaca assamensis','maca_leon-Macaca leonina','maca_maca-Macaque',
# 'maca_mula-Macaca mulatta','maca_munz-Macaca munzala','maca_radi-Macaca radiata','maca_sile-Macaca silenus','mani_cras-Manis crassicaudata',
# 'mart_flav-Martes flavigula','mart_gwat-Martes gwatkinsii','mell_cape-Mellivora capensis','melo_pers','melu_ursi','mosc_indi-Moschiola indica',
# 'munt_munt-Muntiacus muntjak','naem_gora-Naemorhedus goral','neof_nebu-Neofelis nebulosa','nilg_hylo-Nilgiritragus hylocrius',
# 'pagu_larv-Paguma larvata-Masked Palm Civet','pant_pard-Panthera pardus','pant_tigr','para-jerd-Paradoxurus jerdoni','para_herm-Paradoxurus hermaphroditus','pard_marm-Pardofelis marmorata','pavo_cris','prio_beng-Prionailurus bengalensis','prio_pard-Prionodon pardicolor','prio_rubi-Prionailurus rubiginosus',
# 'prio_vive-Prionailurus viverrinus','rusa_unic-Rusa unicolor','semn_ente-Semnopithecus entellus','semn_john+Semnopithecus johnii','sus__scro-Sus scrofa',
# 'tetr_quad-Tetracerus quadricornis','trac_john-Trachypithecus johnii','trac_pile-Trachypithecus pileatus','tree_shre','ursu_thib-Ursus thibetanus',
# 'vara_beng-Varanus bengalensis','vara_salv-Varanus salvator','vehi_vehi','vive_indi-Viverricula indica','vive_zibe-Viverra zibetha','vulp_beng','vulp_vulp']  # class names

names : [
'anat_elli','anti_cerv','arct_coll','athe_macr','axis_axis','axis_porc','bats_bats','bird_bird',
'blan_blan','bos__fron','bos__gaur','bos__indi','bose_trag','budo_taxi','call_pyge','came_came',
'cani_aure','cani_lupu','capr_hisp','capr_thar','cato_temm','catt_catt','catt_kill','cuon_alpi',
'dome_cats','dome_dogs','elep_maxi','equu_caba','feli_chau','feli_sylv','fran_pond','funa_palm',
'gall_gall','gall_lunu','gall_sonn','gall_spad','gaze_benn','goat_sheep','hela_mala','herp_edwa',
'herp_fusc','herp_smit','herp_urva','herp_vitt','homo_sapi','hyae_hyae','hyst_brac','hyst_indi',
'lept_java','lepu_nigr','lutr_lutr','lutr_pers','maca_arct','maca_assa','maca_leon','maca_maca',
'maca_mula','maca_munz','maca_radi','maca_sile','mani_cras','mart_flav','mart_gwat','mell_cape',
'melo_pers','melu_ursi','mosc_indi','munt_munt','naem_gora','neof_nebu','nilg_hylo','pagu_larv',
'pant_pard','pant_tigr','para_jerd','para_herm','pard_marm','pavo_cris','prio_beng','prio_pard',
'prio_rubi','prio_vive','rusa_unic','semn_ente','semn_john','sus__scro','tetr_quad','trac_john',
'trac_pile','tree_shre','ursu_thib','vara_beng','vara_salv','vehi_vehi','vive_indi','vive_zibe',
'vulp_beng','vulp_vulp'
]

# names: ['mani_cras', 'maca_munz', 'maca_radi', 'athe_macr', 'vulp_beng', 'lept_java', 'trac_pile', 'hyst_brac', 'nilg_hylo', 'prio_vive',
#   'neof_nebu', 'melu_ursi', 'vehi_vehi', 'hyae_hyae', 'maca_mula', 'fran_pond', 'munt_munt', 'feli_sylv', 'maca_sile', 'vive_zibe', 'rusa_unic',
#     'lepu_nigr', 'vive_indi', 'pavo_cris', 'anti_cerv', 'gall_lunu', 'cato_temm','sus__scro', 'cani_aure', 'para_herm', 'axis_axis', 'catt_kill',
#      'goat_sheep', 'vara_beng', 'para-jerd', 'mart_gwat', 'homo_sapi', 'semn_joh', 'herp_edwa', 'bos__fron','herp_vitt', 'arct_coll', 'dome_cats', 
#      'bos__indi', 'mell_cape', 'ursu_thib','semn_ente', 'prio_rubi', 'dome_dogs', 'cani_lupu', 'gall_sonn',
#          'gaze_benn', 'bose_trag', 'budo_taxi', 'bos__gaur', 'catt_catt', 'blan_blan',
#           'cuon_alpi-Cuon alpinus', 'capr_thar', 'equu_caba', 'herp_fusc', 'trac_john',
#            'vara_salv', 'gall_gall', 'naem_gora', 'herp_urva', 'hyst_indi',
#             'herp_smit', 'bird_bird', 'tetr_quad-Tetracerus quadricornis', 'feli_chau', 'maca_arct',
#              'lutr_pers', 'mosc_indi', 'pant_tigr', 'pant_pard', 'mart_flav',
#               'pagu_larv', 'prio_beng', 'gall_spad', 'elep_maxi', 'axis_porc', 'anat_elli', 'bats_bats', 'call_pyge', 'came_came', 'capr_hisp', 
#               'funa_palm', 'hela_mala', 'lutr_lutr', 'maca_assa', 'maca_leon', 'maca_maca', 
#                 'melo_pers', 'pard_marm', 'prio_pard', 'tree_shre', 'vulp_vulp']   # class names
# """

#################### Class names for 50% division.
# names: ['mani_cras-Manis crassicaudata', 'maca_munz-Macaca munzala', 'maca_radi-Macaca radiata', 'athe_macr', 'vulp_beng', 'lept_java-Leptoptilos javanicus',
#  'trac_pile-Trachypithecus pileatus', 'hyst_brac-Hystrix brachyura', 'nilg_hylo-Nilgiritragus hylocrius', 'prio_vive-Prionailurus viverrinus',
#   'neof_nebu-Neofelis nebulosa', 'melu_ursi', 'vehi_vehi', 'hyae_hyae-Hyaena hyaena', 'maca_mula-Macaca mulatta', 'fran_pond-Francolinus pondicerianus',
#    'munt_munt-Muntiacus muntjak', 'feli_sylv-Felis sylvestris', 'maca_sile-Macaca silenus', 'vive_zibe-Viverra zibetha', 'rusa_unic-Rusa unicolor',
#     'lepu_nigr-Lepus nigricollis', 'vive_indi-Viverricula indica', 'pavo_cris', 'anti_cerv', 'gall_lunu-Galloperdix lunulata', 'cato_temm-Catopuma temminckii', 
#     'sus__scro-Sus scrofa', 'cani_aure-Canis aureus', 'para_herm-Paradoxurus hermaphroditus', 'axis_axis', 'catt_kill', 'goat_sheep', 'vara_beng-Varanus bengalensis', 
#     'para-jerd-Paradoxurus jerdoni', 'mart_gwat-Martes gwatkinsii', 'homo_sapi', 'semn_john+Semnopithecus johnii', 'herp_edwa-Herpestes edwardsii', 'bos__fron', 
#     'herp_vitt-Herpestes vitticollis', 'arct_coll', 'dome_cats-Domestic cat', 'bos__indi', 'mell_cape-Mellivora capensis', 'ursu_thib-Ursus thibetanus',
#    'semn_ente-Semnopithecus entellus', 'prio_rubi-Prionailurus rubiginosus', 'dome_dogs-Domestic dog', 'cani_lupu-Canis lupus', 'gall_sonn-Gallus sonneratii',
#         'gaze_benn-Gazella bennettii', 'bose_trag-Boselaphus tragocamelus', 'budo_taxi-Budorcas taxicolor', 'bos__gaur', 'catt_catt-Cattle', 'blan_blan',
#          'cuon_alpi-Cuon alpinus', 'capr_thar-Capricornis thar', 'equu_caba-Equus caballus', 'herp_fusc-Herpestes fuscus', 'trac_john-Trachypithecus johnii',
#          'vara_salv-Varanus salvator', 'gall_gall-Gallus gallus', 'naem_gora-Naemorhedus goral', 'herp_urva-Herpestes urva', 'hyst_indi-Hystrix indica',
#          'herp_smit-Herpestes smithii', 'bird_bird', 'tetr_quad-Tetracerus quadricornis', 'feli_chau-Felis chaus', 'maca_arct-Macaca arctoides',
#           'lutr_pers-Lutrogale perspicillata', 'mosc_indi-Moschiola indica', 'pant_tigr', 'pant_pard-Panthera pardus', 'mart_flav-Martes flavigula',
#             'pagu_larv-Paguma larvata-Masked Palm Civet', 'prio_beng-Prionailurus bengalensis', 'gall_spad-Galloperdix spadicea', 'elep_maxi-Elephas maximus',
#              'axis_porc']   

# class names
# names: ['person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat', 'traffic light',
#         'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow',
#         'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee',
#         'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard',
#         'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple',
#         'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch',
#         'potted plant', 'bed', 'dining table', 'toilet', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone',
#         'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear',
#         'hair drier', 'toothbrush']  # class names


# Download script/URL (optional)
# download: |
#   from utils.general import download, Path


#   # Download labels
#   segments = False  # segment or box labels
#   dir = Path(yaml['path'])  # dataset root dir
#   url = 'https://github.com/ultralytics/yolov5/releases/download/v1.0/'
#   urls = [url + ('coco2017labels-segments.zip' if segments else 'coco2017labels.zip')]  # labels
#   download(urls, dir=dir.parent)

#   # Download data
#   urls = ['http://images.cocodataset.org/zips/train2017.zip',  # 19G, 118k images
#           'http://images.cocodataset.org/zips/val2017.zip',  # 1G, 5k images
#           'http://images.cocodataset.org/zips/test2017.zip']  # 7G, 41k images (optional)
#   download(urls, dir=dir / 'images', threads=3)